# shamelessly stolen from https://github.com/fireflysemantics/is/blob/master/.travis.yml
language: node_js
sudo: false
node_js:
  - "stable"

script:
  # Since we are currently only concerned with typedoc...
  - mkdir -p wasm
  - "echo 'export function to_svg(arg0: string): string;' > wasm/diagram.d.ts"

  - npm run doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

before_deploy:
  - touch .nojekyll
  # only let the artifact remain
  - "echo '/*' > .gitignore"
  - "echo '!/typedoc' >> .gitignore"
  - "echo '!/.nojekyll' >> .gitignore"
