[workspace]
members = [
    "rust/diagram",
    "rust/svgbob/svgbob",
]

[profile.release]
lto = true
debug = true        # required by wasm-snip
opt-level = "z"     # Optimize for code size, hard
panic = "abort"
