[package]
name = "diagram"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
svgbob = { path = "../svgbob/svgbob" }
wee_alloc = "0.4.2"
